config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
    skip: [:sessions, :registrations]

  devise_scope :user do
    get "/users", to: "devise/sessions#new", as: :new_user_session
    post "/users/sign_in", to: "devise/sessions#create", as: :user_session
    get "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :leaderboards, only: [:index]
    resources :players, only: [:index, :show, :new, :create]
    resources :seasons, only: [:index, :show]
  end

  get "/:locale", to: "high_voltage/pages#show", id: "home"
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :ladders

  scope :current, -> { where(active: true).order(start: :desc).first }
  scope :published_seasons, -> { where(published: true) }
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.published_seasons.order(start: :desc)
  end

  def show
    @season = Season.find(params[:id])
    @na_ladder = @season.ladders.find_by(region: 'na')
    @na_players = JSON.parse(@na_ladder.json)
    @eu_ladder = @season.ladders.find_by(region: 'eu')
    @eu_players = JSON.parse(@eu_ladder.json)
  end
end

app/views/seasons/index.html.erb
<div class="hero" style="background-image: url(<%= image_path 'texture_crystal2_s.jpg' %>);">
  <div class="hero-overlay bg-opacity-10"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-4xl">
      <h1 class="my-5 text-5xl font-extrabold">PvP League Season Leaderboards</h1>
      <p class="mb-5"></p>
    </div>
  </div>
</div>

<div class="p-4 text-center">
  <h2 class="text-4xl font-extrabold">Seasons</h2>
</div>

<div class="p-4 grid md:grid-cols-2 lg:grid-cols-4 gap-2">
  <% @seasons.each do |season| %>
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h2 class="card-title font-extrabold"><%= link_to season.name, season_path(season) %></h2>
        <p>from <%= l season.start.to_date %> to <%= l season.end.to_date %></p>

        <div class="card-actions justify-end">
          <%= link_to "See the ladder", season_path(season), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/seasons/show.html.erb
<div class="hero" style="background-image: url(<%= image_path 'texture_crystal2_s.jpg' %>);">
  <div class="hero-overlay bg-opacity-10"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-4xl">
      <h1 class="my-5 text-5xl font-extrabold"><%= @season.name %></h1>
      <p class="mb-5"></p>
    </div>
  </div>
</div>

<div class="hero bg-base-100 min-h-screen">
  <div class="mx-auto max-w-md text-center md:max-w-full">
    <div class="my-20 flex flex-col w-full lg:flex-row">
      <div class="grid flex-grow card bg-base-300 rounded-box place-items-center">
        <h2 class="p-4 text-2xl text-center font-extrabold">EU ladder</h2>
        <div class="overflow-x-auto">
          <table class="table table-compact table-zebra w-full">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Rating</th>
                <th>Wins</th>
                <th>Defeats</th>
              </tr>
            </thead>
            <tbody>
              <% @eu_players.each do |player| %>
                <tr>
                  <th>
                    <%= player["rank"] %>
                    <%= "🥇" if player["rank"].eql?(1) %>
                    <%= "🥈" if player["rank"].eql?(2) %>
                    <%= "🥉" if player["rank"].eql?(3) %>
                  </th>
                  <td>
                    <div class="flex items-center space-x-3">
                      <div>
                        <div class="font-bold"><%= player["name"] %></div>
                      </div>
                    </div>
                  </td>
                  <td><%= player["scores"][0]["value"] %></td>
                  <td><%= player["scores"][1]["value"] %></td>
                  <td><%= player["scores"][2]["value"] %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div> 
      </div>
      <div class="divider lg:divider-horizontal"></div> 
      <div class="grid flex-grow card bg-base-300 rounded-box place-items-center">
        <h2 class="p-4 text-2xl text-center font-extrabold">NA ladder</h2>
        <div class="overflow-x-auto">
          <table class="table table-compact table-zebra w-full">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Rating</th>
                <th>Wins</th>
                <th>Defeats</th>
              </tr>
            </thead>
            <tbody>
              <% @na_players.each do |player| %>
                <tr>
                  <th>
                    <%= player["rank"] %>
                    <%= "🥇" if player["rank"].eql?(1) %>
                    <%= "🥈" if player["rank"].eql?(2) %>
                    <%= "🥉" if player["rank"].eql?(3) %>
                  </th>
                  <td>
                    <div class="flex items-center space-x-3">
                      <div>
                        <div class="font-bold"><%= player["name"] %></div>
                      </div>
                    </div>
                  </td>
                  <td><%= player["scores"][0]["value"] %></td>
                  <td><%= player["scores"][1]["value"] %></td>
                  <td><%= player["scores"][2]["value"] %></td>
                </tr>
              <% end %>
              </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>