config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" },
    skip: [:sessions, :registrations]

  devise_scope :user do
    get "/users", to: "devise/sessions#new", as: :new_user_session
    post "/users/sign_in", to: "devise/sessions#create", as: :user_session
    get "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :leaderboards, only: [:index]
    resources :players, only: [:index, :show, :new, :create]
    resources :seasons, only: [:index, :show]
  end

  get "/:locale", to: "high_voltage/pages#show", id: "home"
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user, optional: true
  has_many :player_achievements
  has_many :achievements, through: :player_achievements

  encrypts :api_key

  scope :top_3, -> { where("best_rank IN (?)", [1, 2, 3]) }
  scope :with_titles, -> { where.not(titles: nil) }
  scope :with_api_key, -> { where.not(api_key: nil) }

  include PgSearch::Model
  pg_search_scope :whose_igname_starts_with,
    against: :igname,
    using: {
      tsearch: { prefix: true }
    }

  extend FriendlyId
  friendly_id :igname, use: :slugged

  def achievements_points
    achievements
      .pluck("achievements.tiers").flatten.map { |t| t["points"] }.sum
  end

  def achievements_points_by_group_id(group_id)
    achievement_group = AchievementGroup.find(group_id)
    category_ids = achievement_group.achievement_categories.pluck(:id)
    achievements.where("achievements.achievement_category_id IN (?)", category_ids)
      .pluck("achievements.tiers").flatten.map { |t| t["points"] }.sum
  end

  def achievements_points_by_category_id(category_id)
    achievements_by_category_id(category_id)
      .pluck("achievements.tiers").flatten.map { |t| t["points"] }.sum
  end

  def achievements_by_category_id(category_id)
    achievements.where("achievements.achievement_category_id = ?", category_id)
  end

  def done_achievements
    achievements.where("player_achievements.done = ?", true)
  end

  def done_achievements_count
    done_achievements.count
  end

  def done_achievements_by_category_id(category_id)
    done_achievements.where("achievements.achievement_category_id = ?", category_id)
  end

  def current_player_achievements
    player_achievements.where("player_achievements.done = ?", false)
  end

  def fix_account_name
    connection = Faraday.new(
      url: "https://api.guildwars2.com",
    )
    response = connection.get("/v2/account", {}, { Authorization: "Bearer #{self.api_key}" })
    account = JSON.parse(response.body)
    return if response.body["text"].present?
    self.update(igname: account["name"]) unless self.igname.eql?(account["name"])
  end

  def titles_count
    titles.length
  end

  def update_achievements
    connection = Faraday.new(
      url: "https://api.guildwars2.com",
    )
    response = connection.get("/v2/account/achievements", {}, { Authorization: "Bearer #{self.api_key}" })
    player_achievements = JSON.parse(response.body)
    return if response.body["text"].present?
    player_achievements.each do |achievement|
      a = Achievement.find_by(gw_id: achievement["id"])
      pa = self.player_achievements.where(achievement: a).first_or_initialize
      pa.bits = achievement["bits"]
      pa.current = achievement["current"]
      pa.max = achievement["max"]
      pa.done = achievement["done"]
      pa.repeated = achievement["repeated"]
      pa.unlocked = achievement["unlocked"]
      pa.save
    end
  end

  def update_titles
    connection = Faraday.new(
      url: "https://api.guildwars2.com",
    )
    response = connection.get("/v2/account/titles", {}, { Authorization: "Bearer #{self.api_key}" })
    return if response.body["text"].present?
    player_titles = JSON.parse(response.body)
    self.update(titles: player_titles)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    if params[:q].present?
      @q = params[:q].html_safe
      @pagy, @players = pagy(Player.with_titles.whose_igname_starts_with(@q).order(player_achievements_count: :desc))
      @top_3_players = Player.top_3.whose_igname_starts_with(@q)
    else
      @q = nil
      @pagy, @players = pagy(Player.with_titles.order(player_achievements_count: :desc), items: 10)
      @top_3_players = Player.top_3
    end
  end

  def show
    @player = Player.friendly.find(params[:id])
    @titles = Title.where("gw_id IN (?)", @player.titles) if @player.titles.present?
    @achievement_groups = AchievementGroup.all.includes(:achievement_categories)
  end

  def new
    if current_user
      @player = current_user.players.new
    else
      @player = Player.new
    end
  end

  def create
    connection = Faraday.new(
      url: "https://api.guildwars2.com",
    )
    render :new && return unless player_params[:api_key].length.eql?(72)
    response = connection.get("/v2/account", {}, { Authorization: "Bearer #{player_params[:api_key]}" })
    render :new && return if response.body["text"].present?
    account = JSON.parse(response.body)

    @player = Player.where(igname: account["name"]).first_or_initialize
    @player.api_key = player_params[:api_key]
    @player.user = current_user if current_user

    if @player.save
      @player.update_titles
      @player.update_achievements
      redirect_to player_path(@player)
    else
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:api_key)
  end
end

app/views/players/index.html.erb
<div class="hero" style="background-image: url(<%= image_path 'texture_crystal2_s.jpg' %>);">
  <div class="hero-overlay bg-opacity-10"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-4xl">
      <h1 class="my-5 text-5xl font-extrabold"><%= t "players.plural" %> <span class="badge badge-warning badge-5xl">ALPHA</span></h1>
      <p class="mb-5"></p>
    </div>
  </div>
</div>

<div class="hero bg-base-100 min-h-screen">
  <div class="mx-auto w-md text-center md:w-full lg:w-2/3">
    <div class="md:mt-10 mb-4">
      <%= form_with(url: players_path, method: :get, class: "grid md:grid-cols-2 gap-2") do |form| %>
        <div class="form-control w-full">
          <%= form.label :q, t("players.singular"), class: "label" %>
          <%= form.text_field :q, value: @q, class: "input input-bordered w-full" %>
        </div>
        <div class="form-control w-full">
          <%= form.submit t("search"), class: "md:mt-10 w-full btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="mb-10 flex flex-col w-full lg:flex-row">
      <div class="lg:w-1/2">
        <h2 class="p-4 text-2xl text-center font-extrabold"><%= t "players.plural" %> <span class="badge badge-warning badge-5xl">ALPHA</span></h2>
        <%= link_to t("players.register"), new_player_path, class: "w-full btn btn-primary font-bold mb-4" %>
        <div class="overflow-x-auto">
          <table class="table table-compact table-zebra w-full">
            <thead>
              <tr>
                <th><%= t "players.name" %></th>
                <th><%= t "titles.plural" %></th>
                <th><%= t "achievements.plural" %></th>
              </tr>
            </thead>
            <tbody>
              <% @players.each do |player| %>
                <tr>
                  <th>
                    <%= link_to player.igname, player_path(player) %>
                  </th>
                  <td>
                    <%= player.titles.count %>
                  </td>
                  <td>
                    <%= player.done_achievements.count %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <th colspan="3">
                  <%= link_to t("players.register"), new_player_path, class: "w-full btn btn-primary font-bold" %>
                </th>
              </tr>
            </tbody>
          </table>
        </div>
        <%== pagy_nav(@pagy) %>
      </div>

      <div class="divider lg:divider-horizontal"></div>

      <div class="lg:w-1/2 grid flex-grow card bg-base-300 rounded-box place-items-center">
        <h2 class="p-4 text-2xl text-center font-extrabold"><%= t "players.pvp.top" %></h2>
        <div data-controller="read-more" data-read-more-more-text-value="<%= t "show.more" %>" data-read-more-less-text-value="<%= t "show.less" %>" class="overflow-x-auto">
          <div data-read-more-target="content">
            <table class="table table-compact table-zebra w-full">
              <thead>
                <tr>
                  <th><%= t "players.name" %></th>
                  <th><%= t "players.rank.best" %></th>
                  <th><%= t "players.rating.best" %></th>
                </tr>
              </thead>
              <tbody> 
                <% @top_3_players.order([:best_rank, best_rating: :desc]).first(10).each do |player| %>
                  <tr>
                    <th>
                      <%= link_to player.igname, player_path(player) %>
                    </th>
                    <td>
                      <% if player.best_rank.eql?(1) %>
                        <span class="text-xl">🥇</span>
                      <% elsif player.best_rank.eql?(2) %>
                        <span class="text-lg">🥈</span>
                      <% elsif player.best_rank.eql?(3) %>
                        <span class="text-md">🥉</span>
                      <% end %>
                      <%= player.best_rank %>
                    </td>
                    <td>
                      <%= player.best_rating %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <button data-action="read-more#toggle" class="btn btn-primary my-5"><%= t "show.more" %></button>

          <template data-read-more-target="full">
            <table class="table table-compact table-zebra w-full">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Best rank</th>
                  <th>Best rating</th>
                </tr>
              </thead>
              <tbody> 
                <% @top_3_players.order([:best_rank, best_rating: :desc]).each do |player| %>
                  <tr>
                    <th>
                      <%= link_to player.igname, player_path(player) %>
                    </th>
                    <td>
                      <% if player.best_rank.eql?(1) %>
                        <span class="text-xl">🥇</span>
                      <% elsif player.best_rank.eql?(2) %>
                        <span class="text-lg">🥈</span>
                      <% elsif player.best_rank.eql?(3) %>
                        <span class="text-md">🥉</span>
                      <% end %>
                      <%= player.best_rank %>
                    </td>
                    <td>
                      <%= player.best_rating %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </template>
        </div> 
      </div>

    </div>
  </div>
</div>

app/views/players/new.html.erb
<div class="hero min-h-screen" style="background-image: url(<%= image_path 'texture_crystal2_s.jpg' %>);">
  <div class="hero-overlay bg-opacity-10"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-lg">
      <div class="card w-96 bg-primary shadow-xl">
        <div class="card-body">
          <h2 class="card-title"><%= t("registration.title") %></h2>
          <p><%= t("registration.description_html") %></p>
          <pre>
[x] account
[x] unlocks
[x] progression
          </pre>
          <%= form_with(model: @player) do |form| %>
            <%= form.label :api_key, t("registration.api_key") %>
            <%= form.password_field :api_key, required: true, class: "input w-full mt-2" %>
            <%= form.submit t("registration.submit"), class: "btn btn-success font-bold mt-5" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<div class="hero" style="background-image: url(<%= image_path 'texture_crystal2_s.jpg' %>);">
  <div class="hero-overlay bg-opacity-10"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-4xl">
      <h1 class="my-5 text-5xl font-extrabold"><%= @player.igname %> <span class="badge badge-warning badge-5xl">ALPHA</span></h1>
      <p class="mb-5"></p>
    </div>
  </div>
</div>

<% if defined?(@titles) %>
  <div class="m-6 grid md:grid-cols-2 gap-4 place-content-center">
    <div>
      <h2 class="mb-5 text-4xl font-extrabold"><%= t "titles.plural" %></h2>
      <div class="stats shadow">
        <div class="stat">
          <div class="stat-title"><%= t "titles.count" %></div>
          <div class="stat-value text-success"><%= @titles.count %></div>
          <div class="stat-desc"></div>
        </div>
      </div>
      <div data-controller="reveal" data-reveal-hidden-class="hidden" class="overflow-x-auto">
        <button data-action="click->reveal#toggle" type="button" class="btn btn-primary mb-5"><%= t "titles.plural" %>: <%= t "toggle_me" %></button>
        <table data-reveal-target="item" class="hidden table table-compact table-zebra w-full">
          <thead>
            <tr>
              <th></th>
              <th><%= t "titles.singular" %></th>
            </tr>
          </thead>
          <tbody>
            <% @titles.each do |title| %>
              <tr>
                <td>
                  <% if title.icon_url.present? %>
                    <%= image_tag title.icon_url %>
                  <% end %>
                </td>
                <th>
                  <%= title.name.html_safe %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div>
      <h2 class="mb-5 text-4xl font-extrabold"><%= t "achievements.plural" %></h2>
      <div class="stats shadow">
        <div class="stat">
          <div class="stat-title"><%= t "achievements.done.count" %></div>
          <div class="stat-value text-success"><%= @player.done_achievements.count %></div>
          <div class="stat-desc"></div>
        </div>
      </div>
      <div class="stats shadow">
        <div class="stat">
          <div class="stat-title"><%= t "achievements.points.count" %></div>
          <div class="stat-value text-success flex">
            <%= @player.achievements_points %>
            <%= image_tag "https://render.guildwars2.com/file/6631174867B0D6BC62EE3B3BFF2669336DDAE4DA/866106.png", class: "w-8" %>
          </div>
          <div class="stat-desc"></div>
        </div>
      </div>

      <% @achievement_groups.order(:order).each do |achievement_group| %>
        <div data-controller="reveal" data-reveal-hidden-class="hidden" class="card card-compact bg-shadow-xl">
          <div class="flex justify-between">
            <h2 class="card-title">
              <button data-action="click->reveal#toggle" type="button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5L7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                </svg>
              </button>
                <%= achievement_group.name %>
            </h2>
            <div class="flex">
              <div class="avatar-group -space-x-6">
                <% achievement_group.achievement_categories.pluck(:icon).uniq.first(4).each do |icon| %>
                  <div class="avatar">
                    <div class="w-12 h-12">
                      <%= image_tag icon %>
                    </div>
                  </div>
                  </figure>
                <% end %>
              </div>
              <div class="ml-6 card-title">
                <%= @player.achievements_points_by_group_id(achievement_group.id) %>
                <%= image_tag "https://render.guildwars2.com/file/6631174867B0D6BC62EE3B3BFF2669336DDAE4DA/866106.png", class: "w-8" %>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div data-reveal-target="item" class="hidden">
              <% achievement_group.achievement_categories.order(:order).each do |achievement_category| %>
                <% if @player.achievements_by_category_id(achievement_category.id).any? %>
                  <div class="flex justify-between">
                    <h3 class="card-title">
                      <%= achievement_category.name %>
                    </h3>
                    <div class="flex">
                      <%= image_tag achievement_category.icon, class: "w-12" if achievement_category.icon.present? %>
                      <div class="card-title ml-6">
                        <%= @player.achievements_points_by_category_id(achievement_category.id) %>
                        <%= image_tag "https://render.guildwars2.com/file/6631174867B0D6BC62EE3B3BFF2669336DDAE4DA/866106.png", class: "w-8" %>
                      </div>
                    </div>
                  </div>
                  <table>
                    <% @player.done_achievements_by_category_id(achievement_category.id).each do |achievement| %>
                      <tr>
                        <td>
                          <%= achievement.name %>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="my-5 stats shadow">
        <div class="stat">
          <div class="stat-title"><%= t "achievements.current.count" %></div>
          <div class="stat-value text-warning"><%= @player.current_player_achievements.count %></div>
          <div class="stat-desc"></div>
        </div>
      </div>

      <div data-controller="reveal" data-reveal-hidden-class="hidden" class="overflow-x-auto">
        <button data-action="click->reveal#toggle" type="button" class="btn btn-primary mb-5"><%= t "toggle_me" %></button>
        <table data-reveal-target="item" class="hidden table table-compact table-zebra w-full">
          <thead>
            <tr>
              <td><%= t "achievements.current.progress" %></td>
              <td></td>
              <th><%= t "achievements.singular" %></th>
            </tr>
          </thead>
          <tbody>
            <% @player.current_player_achievements.each do |player_achievement| %>
              <tr>
                <td>
                  <div class="radial-progress" style="--value:<%= player_achievement.progress %>; --size:3rem"><%= player_achievement.progress %>%</div>
                </td>
                <td>
                  <% if player_achievement.achievement.icon_url.present? %>
                    <%= image_tag player_achievement.achievement.icon_url %>
                  <% end %>
                </td>
                <th>
                  <%= player_achievement.achievement.name %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
<% end %>

<% if @player.best_rank.present? %>
  <div class="hero bg-base-100 min-h-screen">
    <div class="mx-auto max-w-md text-center md:max-w-full">
      <div class="flex flex-col w-full lg:flex-row">
        <div class="grid flex-grow h-32 card bg-base-300 rounded-box place-items-center">
          <p class="text-2xl font-extrabold">
          <%= t "players.rank.best" %><br>
          <% if @player.best_rank.eql?(1) %>
            <span class="text-5xl">🥇</span>
          <% elsif @player.best_rank.eql?(2) %>
            <span class="text-4xl">🥈</span>
          <% elsif @player.best_rank.eql?(3) %>
            <span class="text-3xl">🥉</span>
          <% else %>
            <%= @player.best_rank %>
          <% end %>
          </p>
        </div> 
        <div class="divider lg:divider-horizontal"><%= t "and" %></div> 
        <div class="grid flex-grow h-32 card bg-base-300 rounded-box place-items-center">
          <p class="text-2xl font-extrabold"><%= t "players.rating.best" %><br><%= @player.best_rating %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>